name: magdalena
favicon: null
layout_spectrum: 0.5826239266898483
typography_spectrum: 0.16098574688658118
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7541023271623999
  lightness: 0.5196690140292048
  saturation: 0.1142001710832119
  rhythmicContrast: 0.8626154991798103
purpose: []
